import { ReactNode } from 'react';

import { ColorMode, BadgeProps as CUIBadgeProps } from '@chakra-ui/react';

import { Icon } from '../../common/types';
import { Color, FontSizes } from '../../theme/types';

export type Variant = 'contained' | 'outlined' | 'text';

export type Size = keyof Omit<FontSizes, '5xl' | '6xl' | '7xl' | '8xl' | '9xl'> & string;

export type RenderProps = {
	color?: keyof Color;
	colorMode?: ColorMode;
	height?: string;
	size?: Size;
	fontSize?: string;
};

export type BadgeProps = {
	children: ReactNode;
	color?: keyof Color;
	colorMode?: ColorMode;
	renderLeft?: (props: RenderProps) => Icon;
	renderRight?: (props: RenderProps) => Icon;
	isLight?: boolean;
	isLoading?: boolean;
	size?: Size;
	variant?: Variant;
} & Omit<
	CUIBadgeProps,
	// Box Props
	| 'as'
	| 'p'
	| 'pt'
	| 'pr'
	| 'pe'
	| 'pb'
	| 'pl'
	| 'ps'
	| 'px'
	| 'py'
	| 'padding'
	| 'paddingTop'
	| 'paddingRight'
	| 'paddingEnd'
	| 'paddingBottom'
	| 'paddingLeft'
	| 'paddingStart'
	| 'color'
	| 'bg'
	| 'background'
	| 'backgroundColor'
	| 'bgColor'
	| 'opacity'
	| 'bgGradient'
	| 'bgClip'
	| 'backgroundClip'
	| 'fontFamily'
	| 'fontSize'
	| 'fontWeight'
	| 'lineHeight'
	| 'letterSpacing'
	| 'textAlign'
	| 'fontStyle'
	| 'textTransform'
	| 'textDecoration'
	| 'w'
	| 'h'
	| 'minW'
	| 'maxW'
	| 'minH'
	| 'maxH'
	| 'd'
	| 'width'
	| 'height'
	| 'minWidth'
	| 'maxWidth'
	| 'minHeight'
	| 'maxHeight'
	| 'display'
	| 'boxSize'
	| 'verticalAlign'
	| 'overflow'
	| 'overflowX'
	| 'overflowY'
	| 'alignItems'
	| 'align'
	| 'alignContent'
	| 'justifyItems'
	| 'justifyContent'
	| 'justify'
	| 'flexWrap'
	| 'wrap'
	| 'flexDirection'
	| 'flexDir'
	| 'direction'
	| 'flex'
	| 'flexGrow'
	| 'flexShrink'
	| 'flexBasis'
	| 'justifySelf'
	| 'alignSelf'
	| 'order'
	| 'gridGap'
	| 'gap'
	| 'gridRowGap'
	| 'rowGap'
	| 'gridColumnGap'
	| 'columnGap'
	| 'gridColumn'
	| 'column'
	| 'gridRow'
	| 'row'
	| 'gridArea'
	| 'area'
	| 'gridAutoFlow'
	| 'autoFlow'
	| 'gridAutoRows'
	| 'autoRows'
	| 'gridAutoColumns'
	| 'autoColumns'
	| 'gridTemplateRows'
	| 'templateRows'
	| 'gridTemplateColumns'
	| 'templateColumns'
	| 'gridTemplateAreas'
	| 'templateAreas'
	| 'bg'
	| 'background'
	| 'bgImage'
	| 'backgroundImage'
	| 'bgSize'
	| 'backgroundSize'
	| 'bgPosition'
	| 'backgroundPosition'
	| 'bgRepeat'
	| 'backgroundRepeat'
	| 'bgAttachment'
	| 'backgroundAttachment'
	| 'border'
	| 'borderWidth'
	| 'borderStyle'
	| 'borderColor'
	| 'borderTop'
	| 'borderTopWidth'
	| 'borderTopStyle'
	| 'borderTopColor'
	| 'borderRight'
	| 'borderEnd'
	| 'borderRightWidth'
	| 'borderEndWidth'
	| 'borderRightStyle'
	| 'borderEndStyle'
	| 'borderRightColor'
	| 'borderEndColor'
	| 'borderBottom'
	| 'borderBottomWidth'
	| 'borderBottomStyle'
	| 'borderBottomColor'
	| 'borderLeft'
	| 'borderStart'
	| 'borderLeftWidth'
	| 'borderStartWidth'
	| 'borderLeftStyle'
	| 'borderStartStyle'
	| 'borderLeftColor'
	| 'borderStartColor'
	| 'borderX'
	| 'borderY'
	| 'borderRadius'
	| 'borderTopLeftRadius'
	| 'borderTopStartRadius'
	| 'borderTopRightRadius'
	| 'borderTopEndRadius'
	| 'borderBottomRightRadius'
	| 'borderBottomEndRadius'
	| 'borderBottomLeftRadius'
	| 'borderBottomStartRadius'
	| 'borderTopRadius'
	| 'borderRightRadius'
	| 'borderEndRadius'
	| 'borderBottomRadius'
	| 'borderLeftRadius'
	| 'borderStartRadius'
	| 'pos'
	| 'position'
	| 'zIndex'
	| 'top'
	| 'right'
	| 'bottom'
	| 'left'
	| 'filter'
	| 'blur'
	| 'brightness'
	| 'contrast'
	| 'hueRotate'
	| 'invert'
	| 'saturate'
	| 'dropShadow'
	| 'backdropFilter'
	| 'backdropBlur'
	| 'backdropBrightness'
	| 'backdropContrast'
	| 'backdropHueRotate'
	| 'backdropInvert'
	| 'backdropSaturate'
	| 'animation'
	| 'appearance'
	| 'transform'
	| 'transformOrigin'
	| 'visibility'
	| 'whiteSpace'
	| 'userSelect'
	| 'pointerEvents'
	| 'wordBreak'
	| 'overflowWrap'
	| 'textOverflow'
	| 'boxSizing'
	| 'cursor'
	| 'resize'
	| 'transition'
	| 'objectFit'
	| 'objectPosition'
	| 'float'
	| 'fill'
	| 'stroke'
	| 'outline'
	// CUI Badge Props
	| 'colorScheme'
	| 'size'
	| 'variant'
>;
