root: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

settings: 
  "import/resolver": 
    "node":
      "extensions": [".js", ".jsx", ".ts", ".tsx"]
  react:
    version: "detect"

env:
  browser: true
  amd: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:react-hooks/recommended"
  - "plugin:prettier/recommended"
  - "prettier/react"

rules: 
  "react/react-in-jsx-scope": "off"
  "react/prop-types": "off"
  "react-hooks/exhaustive-deps": "off"
  "jsx-a11y/anchor-is-valid":
    - "error"
    - components:
        - "Link"
      specialLink: 
        - "hrefLeft"
        - "hrefRight"
      aspects:
        - "invalidHref"
        - "preferButton"
  "import/order":
    - "error"
    - groups:
        - "builtin"
        - "external"
        - "internal"
        - "sibling"
        - "parent"
        - "object"
        - "index"
      pathGroups:
        - pattern: "react*"
          group: "external"
          position: "before"
      pathGroupsExcludedImportTypes:
        - "react*"
      new1ines-between: "always"
      alphabetize:
        order: "asc"
        caseInsensitive: true